spring.application.name=E-Ticket

server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.jpa.hibernate.ddl-auto=validate

eticket.jwt.secret=${ETICKET_JWT_SECRET}
eticket.jwt.expiration=3600
eticket.invitation.expiration=PT24H

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${ETICKET_MAIL_USERNAME}
spring.mail.password=${ETICKET_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true