CREATE TABLE tickets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200) NOT NULL,
    description     CLOB NOT NULL,
    requester_email VARCHAR(255) NOT NULL,
    priority        VARCHAR(20) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    due_date        DATE,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL
);