CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(20) NOT NULL,
    organization_id BIGINT,
    created_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

INSERT INTO users (username, email, password_hash, role, organization_id, created_at)
VALUES ('admin', 'admin@eticket.local', '$2a$10$z3se42R56ynsu.FQFfzTaOU6nuSQOWBZPNzOqNi07egahm0w5QNjK', 'ADMIN', NULL, CURRENT_TIMESTAMP);
