CREATE TABLE invitations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash      VARCHAR(64) NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL,
    organization_id BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    used_at         TIMESTAMP,
    CONSTRAINT fk_invitations_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);
